# Generated by Django 5.0 on 2024-01-02 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
        ('flow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AddField(
            model_name='autorization',
            name='cargo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authorization.cargo'),
        ),
        migrations.AddField(
            model_name='autorization',
            name='flowAuth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flow.flow'),
        ),
        migrations.AddField(
            model_name='autorization',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
