# Generated by Django 5.0 on 2024-01-02 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('pesquisavel', models.BooleanField(default=False)),
                ('editavel', models.BooleanField(default=False)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow.data')),
            ],
        ),
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_processo', models.CharField(max_length=50)),
                ('module', models.CharField(max_length=50)),
                ('organization', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('state', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Flow',
                'verbose_name_plural': 'Flows',
                'unique_together': {('id_processo', 'module', 'organization')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_transacao', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('state', models.BooleanField(default=True)),
                ('reprocessavel', models.BooleanField(default=False)),
                ('gerenciavel', models.BooleanField(default=False)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow.flow')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
            },
        ),
        migrations.CreateModel(
            name='DestinyCon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('protocol', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('idDestiny', models.CharField(max_length=50)),
                ('notif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow.notification')),
            ],
        ),
        migrations.CreateModel(
            name='OriginCon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('protocol', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('idOrigin', models.CharField(max_length=50)),
                ('notif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow.notification')),
            ],
        ),
        migrations.CreateModel(
            name='Regras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('prompt', models.CharField(max_length=50)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow.campo')),
            ],
        ),
    ]
