# Generated by Django 3.0.7 on 2024-01-03 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Data',
                'verbose_name_plural': 'Datas',
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('typeField', models.CharField(max_length=50)),
                ('searchable', models.BooleanField(default=False)),
                ('editable', models.BooleanField(default=False)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow.Data')),
            ],
            options={
                'verbose_name': 'Field',
                'verbose_name_plural': 'Fields',
            },
        ),
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_id', models.CharField(max_length=50)),
                ('module', models.CharField(max_length=50)),
                ('organization', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('state', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Flow',
                'verbose_name_plural': 'Flows',
                'unique_together': {('process_id', 'module', 'organization')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=50)),
                ('typeNotification', models.CharField(max_length=50)),
                ('state', models.BooleanField(default=True)),
                ('reprocessable', models.BooleanField(default=False)),
                ('manageable', models.BooleanField(default=False)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow.Flow')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeRules', models.CharField(max_length=50)),
                ('prompt', models.CharField(max_length=50)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow.Field')),
            ],
            options={
                'verbose_name': 'Rule',
                'verbose_name_plural': 'Rules',
            },
        ),
        migrations.CreateModel(
            name='OriginConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeOriginConnection', models.CharField(max_length=50)),
                ('protocol', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('origin_id', models.CharField(max_length=50)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow.Notification')),
            ],
            options={
                'verbose_name': 'Origin Connection',
                'verbose_name_plural': 'Origin Connections',
            },
        ),
        migrations.CreateModel(
            name='DestinyConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeDestinyConnection', models.CharField(max_length=50)),
                ('protocol', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('destiny_id', models.CharField(max_length=50)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow.Notification')),
            ],
            options={
                'verbose_name': 'Destiny Connection',
                'verbose_name_plural': 'Destiny Connections',
            },
        ),
    ]
